# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lauren Hirata Singh
tagline:             'A technical writing-ish blog'
description:         ''
url:                 http://lnhsingh.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lauren Hirata Singh
  url:               https://twitter.com/lnhsingh             

# Custom vars
version:             1.0.0
