---
author:
  name: "Lauren Hirata Singh"
  url: "https://twitter.com/lnhsingh"
baseurl: ""
description: "A blog that's semi related to technical writing."
google_analytics_id: UA-163964195-1
paginate: 5
permalink: pretty
plugins:
  - jekyll-paginate
tagline: "A technical writing-ish blog"
title: "Lauren Hirata Singh"
url: "http://lnhsingh.com"
version: "1.1.0"
